apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
  namespace: devhub
spec:
  application:
    appConfig:
      configMaps:
        - name: developer-hub-app-config
        - name: developer-hub-rbac-config
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: developer-hub-dynamic-plugins
    extraEnvs:
      secrets:
        - name: secrets-rhdh
    extraFiles:
      configMaps:
        - name: developer-hub-rbac-policy
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true