kind: ConfigMap
apiVersion: v1
metadata:
  name: developer-hub-rbac-config
  namespace: devhub
data:
  rhdh-config-rbac.yaml: |
    permission:
      enabled: true
      rbac:
        policies-csv-file: ./rbac-policy.csv
        admin:
          users:
            - name: user:default/derekwaters