kind: Secret
apiVersion: v1
metadata:
  name: secrets-rhdh
  namespace: devhub
data:
  BACKEND_SECRET: TODO_BASE64
  GITHUB_ACCESS_TOKEN: TODO_BASE64
  GITHUB_CLIENT_ID: TODO_BASE64
  GITHUB_CLIENT_SECRET: TODO_BASE64
type: Opaque